# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c0174f27a959e3753c2a9b68f66c991d79420b3b0282a804265a9cfa0c9e92eca62639c05ba3e2fad8bb340d994aff405eec3c45de425ddac9a2006fec450f6

test:
  secret_key_base: 76e2890652d160bff323e037ae6d01b04df01060a9e09577aa0d6d858fb7186d756f5a79e01e0b2998acda8ed885cdc8c63b0a8de4388eda8e0113b08e1084cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
